language: node_js
node_js:
  - "5"
  - "4"
os:
  - linux
  - osx
  - windows
script: npm run coverage
# Send coverage data to Coveralls
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js